// app/layout.tsx

import type { Metadata } from "next";
import React from "react";
import { Inter } from "next/font/google";
import "./app.css";
import AuthWrapper from "./components/AuthWrapper"; // <- nuevo componente

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthWrapper>{children}</AuthWrapper>
      </body>
    </html>
  );
}

